name: Build succeed on PR

on:
  pull_request:
    branches:
      - main
    
jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/stepup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        runs: npm run install
      
      - name: Run Build
        runs: npm run build
