name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: manabdebnath/echohub:latest
          build-args: |
            NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}

      - name: Verify Pushed Image
        run: docker pull manabdebnath/echohub:latest

      - name: Deploy EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop web-app || true
            docker rm web-app || true
            docker rmi manabdebnath/echohub:latest || true
            docker pull manabdebnath/echohub:latest
            docker run -d \
              --name web-app \
              --restart unless-stopped \
              -p 3000:3000 \
              -e NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT=${{ secrets.IMAGEKIT_URL_ENDPOINT }} \
              -e NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY=${{ secrets.IMAGEKIT_PUBLIC_KEY }} \
              -e PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }} \
              -e CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} \
              -e CLERK_WEBHOOK_SIGNING_SECRET=${{ secrets.CLERK_WEBHOOK_SIGNING_SECRET }} \
              -e NODE_ENV=production \
              -e HOSTNAME=0.0.0.0 \
              manabdebnath/echohub:latest
              docker exec web-app npx prisma migrate deploy